/// W4.5 — canonical [ProjectCalculationRecord], owned by the Projects domain.
///
/// A single saved calculator result attached to a Project via [projectId].
/// The record stores immutable, JSON-safe snapshots of the calculator input and
/// output captured at save time (copy-on-save). It is a separate Project-owned
/// entity; [Project] itself is unchanged.
///
/// [id] and [createdAt] are generated by the Projects save path, never by the
/// calculator (Tools) presentation. [calculatorVersion] identifies the snapshot
/// schema version, NOT the app/package version.
class ProjectCalculationRecord {
  final String id;
  final String projectId;
  final String calculatorId;
  final String calculatorVersion;
  final String? title;
  final Map<String, Object?> inputSnapshot;
  final Map<String, Object?> outputSnapshot;
  final DateTime createdAt;

  const ProjectCalculationRecord({
    required this.id,
    required this.projectId,
    required this.calculatorId,
    required this.calculatorVersion,
    this.title,
    required this.inputSnapshot,
    required this.outputSnapshot,
    required this.createdAt,
  });

  ProjectCalculationRecord copyWith({
    String? id,
    String? projectId,
    String? calculatorId,
    String? calculatorVersion,
    String? title,
    bool clearTitle = false,
    Map<String, Object?>? inputSnapshot,
    Map<String, Object?>? outputSnapshot,
    DateTime? createdAt,
  }) {
    return ProjectCalculationRecord(
      id: id ?? this.id,
      projectId: projectId ?? this.projectId,
      calculatorId: calculatorId ?? this.calculatorId,
      calculatorVersion: calculatorVersion ?? this.calculatorVersion,
      title: clearTitle ? null : (title ?? this.title),
      inputSnapshot: inputSnapshot ?? this.inputSnapshot,
      outputSnapshot: outputSnapshot ?? this.outputSnapshot,
      createdAt: createdAt ?? this.createdAt,
    );
  }
}
