import '../../../../../localization/ar.dart';
import '../../../../../localization/en.dart';

class L10n {
  final bool isArabic;
  const L10n(this.isArabic);

  String call(String key) => isArabic ? (_ar[key] ?? key) : (_en[key] ?? key);

  static const Map<String, String> _ar = {
    // Categories
    'catConcrete': Ar.inspectionCatConcrete,
    'catReinforcement': Ar.inspectionCatReinforcement,
    'catMasonry': Ar.inspectionCatMasonry,
    'catPlastering': Ar.inspectionCatPlastering,
    'catTiles': Ar.inspectionCatTiles,
    'catWaterproofing': Ar.inspectionCatWaterproofing,
    'catPainting': Ar.inspectionCatPainting,
    'catExcavation': Ar.inspectionCatExcavation,
    'catAsphalt': Ar.inspectionCatAsphalt,
    'catMep': Ar.inspectionCatMep,
    'catSafety': Ar.inspectionCatSafety,

    // Concrete Works
    'itemConc01': Ar.inspectionItemConc01,
    'itemConc01D': Ar.inspectionItemConc01Desc,
    'itemConc02': Ar.inspectionItemConc02,
    'itemConc02D': Ar.inspectionItemConc02Desc,
    'itemConc03': Ar.inspectionItemConc03,
    'itemConc03D': Ar.inspectionItemConc03Desc,
    'itemConc04': Ar.inspectionItemConc04,
    'itemConc05': Ar.inspectionItemConc05,
    'itemConc05D': Ar.inspectionItemConc05Desc,
    'itemConc06': Ar.inspectionItemConc06,
    'itemConc07': Ar.inspectionItemConc07,
    'itemConc07D': Ar.inspectionItemConc07Desc,
    'itemConc08': Ar.inspectionItemConc08,
    'itemConc09': Ar.inspectionItemConc09,
    'itemConc09D': Ar.inspectionItemConc09Desc,
    'itemConc10': Ar.inspectionItemConc10,
    'itemConc11': Ar.inspectionItemConc11,
    'itemConc12': Ar.inspectionItemConc12,
    'itemConc13': Ar.inspectionItemConc13,
    'itemConc13D': Ar.inspectionItemConc13Desc,
    'itemConc14': Ar.inspectionItemConc14,

    // Reinforcement
    'itemReinf01': Ar.inspectionItemReinf01,
    'itemReinf02': Ar.inspectionItemReinf02,
    'itemReinf02D': Ar.inspectionItemReinf02Desc,
    'itemReinf03': Ar.inspectionItemReinf03,
    'itemReinf03D': Ar.inspectionItemReinf03Desc,
    'itemReinf04': Ar.inspectionItemReinf04,
    'itemReinf04D': Ar.inspectionItemReinf04Desc,
    'itemReinf05': Ar.inspectionItemReinf05,
    'itemReinf05D': Ar.inspectionItemReinf05Desc,
    'itemReinf06': Ar.inspectionItemReinf06,
    'itemReinf06D': Ar.inspectionItemReinf06Desc,
    'itemReinf07': Ar.inspectionItemReinf07,
    'itemReinf08': Ar.inspectionItemReinf08,
    'itemReinf08D': Ar.inspectionItemReinf08Desc,
    'itemReinf09': Ar.inspectionItemReinf09,
    'itemReinf09D': Ar.inspectionItemReinf09Desc,
    'itemReinf10': Ar.inspectionItemReinf10,
    'itemReinf11': Ar.inspectionItemReinf11,
    'itemReinf12': Ar.inspectionItemReinf12,

    // Masonry
    'itemMas01': Ar.inspectionItemMas01,
    'itemMas02': Ar.inspectionItemMas02,
    'itemMas03': Ar.inspectionItemMas03,
    'itemMas03D': Ar.inspectionItemMas03Desc,
    'itemMas04': Ar.inspectionItemMas04,
    'itemMas05': Ar.inspectionItemMas05,
    'itemMas06': Ar.inspectionItemMas06,
    'itemMas07': Ar.inspectionItemMas07,
    'itemMas08': Ar.inspectionItemMas08,

    // Plastering
    'itemPlas01': Ar.inspectionItemPlas01,
    'itemPlas01D': Ar.inspectionItemPlas01Desc,
    'itemPlas02': Ar.inspectionItemPlas02,
    'itemPlas03': Ar.inspectionItemPlas03,
    'itemPlas04': Ar.inspectionItemPlas04,
    'itemPlas05': Ar.inspectionItemPlas05,
    'itemPlas06': Ar.inspectionItemPlas06,
    'itemPlas07': Ar.inspectionItemPlas07,
    'itemPlas08': Ar.inspectionItemPlas08,

    // Tiles
    'itemTile01': Ar.inspectionItemTile01,
    'itemTile02': Ar.inspectionItemTile02,
    'itemTile03': Ar.inspectionItemTile03,
    'itemTile04': Ar.inspectionItemTile04,
    'itemTile05': Ar.inspectionItemTile05,
    'itemTile06': Ar.inspectionItemTile06,
    'itemTile07': Ar.inspectionItemTile07,
    'itemTile08': Ar.inspectionItemTile08,

    // Waterproofing
    'itemWpr01': Ar.inspectionItemWpr01,
    'itemWpr01D': Ar.inspectionItemWpr01Desc,
    'itemWpr02': Ar.inspectionItemWpr02,
    'itemWpr03': Ar.inspectionItemWpr03,
    'itemWpr04': Ar.inspectionItemWpr04,
    'itemWpr05': Ar.inspectionItemWpr05,
    'itemWpr06': Ar.inspectionItemWpr06,
    'itemWpr07': Ar.inspectionItemWpr07,
    'itemWpr08': Ar.inspectionItemWpr08,
    'itemWpr09': Ar.inspectionItemWpr09,

    // Painting
    'itemPaint01': Ar.inspectionItemPaint01,
    'itemPaint01D': Ar.inspectionItemPaint01Desc,
    'itemPaint02': Ar.inspectionItemPaint02,
    'itemPaint03': Ar.inspectionItemPaint03,
    'itemPaint04': Ar.inspectionItemPaint04,
    'itemPaint05': Ar.inspectionItemPaint05,
    'itemPaint06': Ar.inspectionItemPaint06,

    // Excavation
    'itemExc01': Ar.inspectionItemExc01,
    'itemExc01D': Ar.inspectionItemExc01Desc,
    'itemExc02': Ar.inspectionItemExc02,
    'itemExc03': Ar.inspectionItemExc03,
    'itemExc04': Ar.inspectionItemExc04,
    'itemExc05': Ar.inspectionItemExc05,
    'itemExc06': Ar.inspectionItemExc06,
    'itemExc07': Ar.inspectionItemExc07,
    'itemExc08': Ar.inspectionItemExc08,
    'itemExc09': Ar.inspectionItemExc09,
    'itemExc10': Ar.inspectionItemExc10,

    // Asphalt
    'itemAsph01': Ar.inspectionItemAsph01,
    'itemAsph01D': Ar.inspectionItemAsph01Desc,
    'itemAsph02': Ar.inspectionItemAsph02,
    'itemAsph02D': Ar.inspectionItemAsph02Desc,
    'itemAsph03': Ar.inspectionItemAsph03,
    'itemAsph04': Ar.inspectionItemAsph04,
    'itemAsph05': Ar.inspectionItemAsph05,
    'itemAsph06': Ar.inspectionItemAsph06,
    'itemAsph07': Ar.inspectionItemAsph07,
    'itemAsph08': Ar.inspectionItemAsph08,

    // MEP
    'itemMep01': Ar.inspectionItemMep01,
    'itemMep02': Ar.inspectionItemMep02,
    'itemMep03': Ar.inspectionItemMep03,
    'itemMep04': Ar.inspectionItemMep04,
    'itemMep05': Ar.inspectionItemMep05,
    'itemMep06': Ar.inspectionItemMep06,
    'itemMep07': Ar.inspectionItemMep07,
    'itemMep08': Ar.inspectionItemMep08,
    'itemMep09': Ar.inspectionItemMep09,
    'itemMep10': Ar.inspectionItemMep10,

    // Safety
    'itemSafe01': Ar.inspectionItemSafe01,
    'itemSafe02': Ar.inspectionItemSafe02,
    'itemSafe03': Ar.inspectionItemSafe03,
    'itemSafe04': Ar.inspectionItemSafe04,
    'itemSafe05': Ar.inspectionItemSafe05,
    'itemSafe06': Ar.inspectionItemSafe06,
    'itemSafe07': Ar.inspectionItemSafe07,
    'itemSafe08': Ar.inspectionItemSafe08,
    'itemSafe09': Ar.inspectionItemSafe09,
    'itemSafe10': Ar.inspectionItemSafe10,
  };

  static const Map<String, String> _en = {
    // Categories
    'catConcrete': En.inspectionCatConcrete,
    'catReinforcement': En.inspectionCatReinforcement,
    'catMasonry': En.inspectionCatMasonry,
    'catPlastering': En.inspectionCatPlastering,
    'catTiles': En.inspectionCatTiles,
    'catWaterproofing': En.inspectionCatWaterproofing,
    'catPainting': En.inspectionCatPainting,
    'catExcavation': En.inspectionCatExcavation,
    'catAsphalt': En.inspectionCatAsphalt,
    'catMep': En.inspectionCatMep,
    'catSafety': En.inspectionCatSafety,

    // Concrete Works
    'itemConc01': En.inspectionItemConc01,
    'itemConc01D': En.inspectionItemConc01Desc,
    'itemConc02': En.inspectionItemConc02,
    'itemConc02D': En.inspectionItemConc02Desc,
    'itemConc03': En.inspectionItemConc03,
    'itemConc03D': En.inspectionItemConc03Desc,
    'itemConc04': En.inspectionItemConc04,
    'itemConc05': En.inspectionItemConc05,
    'itemConc05D': En.inspectionItemConc05Desc,
    'itemConc06': En.inspectionItemConc06,
    'itemConc07': En.inspectionItemConc07,
    'itemConc07D': En.inspectionItemConc07Desc,
    'itemConc08': En.inspectionItemConc08,
    'itemConc09': En.inspectionItemConc09,
    'itemConc09D': En.inspectionItemConc09Desc,
    'itemConc10': En.inspectionItemConc10,
    'itemConc11': En.inspectionItemConc11,
    'itemConc12': En.inspectionItemConc12,
    'itemConc13': En.inspectionItemConc13,
    'itemConc13D': En.inspectionItemConc13Desc,
    'itemConc14': En.inspectionItemConc14,

    // Reinforcement
    'itemReinf01': En.inspectionItemReinf01,
    'itemReinf02': En.inspectionItemReinf02,
    'itemReinf02D': En.inspectionItemReinf02Desc,
    'itemReinf03': En.inspectionItemReinf03,
    'itemReinf03D': En.inspectionItemReinf03Desc,
    'itemReinf04': En.inspectionItemReinf04,
    'itemReinf04D': En.inspectionItemReinf04Desc,
    'itemReinf05': En.inspectionItemReinf05,
    'itemReinf05D': En.inspectionItemReinf05Desc,
    'itemReinf06': En.inspectionItemReinf06,
    'itemReinf06D': En.inspectionItemReinf06Desc,
    'itemReinf07': En.inspectionItemReinf07,
    'itemReinf08': En.inspectionItemReinf08,
    'itemReinf08D': En.inspectionItemReinf08Desc,
    'itemReinf09': En.inspectionItemReinf09,
    'itemReinf09D': En.inspectionItemReinf09Desc,
    'itemReinf10': En.inspectionItemReinf10,
    'itemReinf11': En.inspectionItemReinf11,
    'itemReinf12': En.inspectionItemReinf12,

    // Masonry
    'itemMas01': En.inspectionItemMas01,
    'itemMas02': En.inspectionItemMas02,
    'itemMas03': En.inspectionItemMas03,
    'itemMas03D': En.inspectionItemMas03Desc,
    'itemMas04': En.inspectionItemMas04,
    'itemMas05': En.inspectionItemMas05,
    'itemMas06': En.inspectionItemMas06,
    'itemMas07': En.inspectionItemMas07,
    'itemMas08': En.inspectionItemMas08,

    // Plastering
    'itemPlas01': En.inspectionItemPlas01,
    'itemPlas01D': En.inspectionItemPlas01Desc,
    'itemPlas02': En.inspectionItemPlas02,
    'itemPlas03': En.inspectionItemPlas03,
    'itemPlas04': En.inspectionItemPlas04,
    'itemPlas05': En.inspectionItemPlas05,
    'itemPlas06': En.inspectionItemPlas06,
    'itemPlas07': En.inspectionItemPlas07,
    'itemPlas08': En.inspectionItemPlas08,

    // Tiles
    'itemTile01': En.inspectionItemTile01,
    'itemTile02': En.inspectionItemTile02,
    'itemTile03': En.inspectionItemTile03,
    'itemTile04': En.inspectionItemTile04,
    'itemTile05': En.inspectionItemTile05,
    'itemTile06': En.inspectionItemTile06,
    'itemTile07': En.inspectionItemTile07,
    'itemTile08': En.inspectionItemTile08,

    // Waterproofing
    'itemWpr01': En.inspectionItemWpr01,
    'itemWpr01D': En.inspectionItemWpr01Desc,
    'itemWpr02': En.inspectionItemWpr02,
    'itemWpr03': En.inspectionItemWpr03,
    'itemWpr04': En.inspectionItemWpr04,
    'itemWpr05': En.inspectionItemWpr05,
    'itemWpr06': En.inspectionItemWpr06,
    'itemWpr07': En.inspectionItemWpr07,
    'itemWpr08': En.inspectionItemWpr08,
    'itemWpr09': En.inspectionItemWpr09,

    // Painting
    'itemPaint01': En.inspectionItemPaint01,
    'itemPaint01D': En.inspectionItemPaint01Desc,
    'itemPaint02': En.inspectionItemPaint02,
    'itemPaint03': En.inspectionItemPaint03,
    'itemPaint04': En.inspectionItemPaint04,
    'itemPaint05': En.inspectionItemPaint05,
    'itemPaint06': En.inspectionItemPaint06,

    // Excavation
    'itemExc01': En.inspectionItemExc01,
    'itemExc01D': En.inspectionItemExc01Desc,
    'itemExc02': En.inspectionItemExc02,
    'itemExc03': En.inspectionItemExc03,
    'itemExc04': En.inspectionItemExc04,
    'itemExc05': En.inspectionItemExc05,
    'itemExc06': En.inspectionItemExc06,
    'itemExc07': En.inspectionItemExc07,
    'itemExc08': En.inspectionItemExc08,
    'itemExc09': En.inspectionItemExc09,
    'itemExc10': En.inspectionItemExc10,

    // Asphalt
    'itemAsph01': En.inspectionItemAsph01,
    'itemAsph01D': En.inspectionItemAsph01Desc,
    'itemAsph02': En.inspectionItemAsph02,
    'itemAsph02D': En.inspectionItemAsph02Desc,
    'itemAsph03': En.inspectionItemAsph03,
    'itemAsph04': En.inspectionItemAsph04,
    'itemAsph05': En.inspectionItemAsph05,
    'itemAsph06': En.inspectionItemAsph06,
    'itemAsph07': En.inspectionItemAsph07,
    'itemAsph08': En.inspectionItemAsph08,

    // MEP
    'itemMep01': En.inspectionItemMep01,
    'itemMep02': En.inspectionItemMep02,
    'itemMep03': En.inspectionItemMep03,
    'itemMep04': En.inspectionItemMep04,
    'itemMep05': En.inspectionItemMep05,
    'itemMep06': En.inspectionItemMep06,
    'itemMep07': En.inspectionItemMep07,
    'itemMep08': En.inspectionItemMep08,
    'itemMep09': En.inspectionItemMep09,
    'itemMep10': En.inspectionItemMep10,

    // Safety
    'itemSafe01': En.inspectionItemSafe01,
    'itemSafe02': En.inspectionItemSafe02,
    'itemSafe03': En.inspectionItemSafe03,
    'itemSafe04': En.inspectionItemSafe04,
    'itemSafe05': En.inspectionItemSafe05,
    'itemSafe06': En.inspectionItemSafe06,
    'itemSafe07': En.inspectionItemSafe07,
    'itemSafe08': En.inspectionItemSafe08,
    'itemSafe09': En.inspectionItemSafe09,
    'itemSafe10': En.inspectionItemSafe10,
  };
}
